# -*- coding: utf-8 -*-
"""Descriptive_Analysis,ipl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEZSLT0ufDl2AEiDuritOElm92MErNwK
"""

import pandas as pd

i=pd.read_csv("/content/ipl_matches_2026.csv")

i.head()

i.shape

i.info()

i.describe()

#missing values
i.isnull().sum()

i.isna().sum()

i.duplicated().sum()

i["season"]

sns.countplot(x=i["season"])      # Good
sns.countplot(data=i, x="season") # Best for DataFrames

tm = pd.concat([i["team1"], i["team2"]])
tm.value_counts()

i["winner"].value_counts().plot(kind="bar")

i["toss_winner"].value_counts().plot(kind="line",marker="d")

i["toss_decision"].value_counts().plot(kind="line",marker="d")

i["player_of_match"].value_counts().plot(
    kind="line",
    marker="d",
    figsize=(10, 10)
)

i['team1_wickets'].value_counts().plot(kind='bar')

i.sort_values(by="team1_wickets")

i['player_of_match'].value_counts().head(10).plot(kind="bar")

i[["team1","team2"]].value_counts().head(10).plot(kind="bar")

vw=i.groupby(["venue","winner"]).size().sort_values(ascending=False)
vw

i.describe()

i.info()

e=i[i["result_type"] != "complete"].value_counts()
e

i.loc[i["result_type"] != "complete", "result_type"]

i.head()

tm = i[i["result_type"] == "tie"]
tm

i[["team1","team2","venue"]]

i["venue"].value_counts()

i["city"].value_counts()

i["city"].value_counts().plot(kind="bar")

i.groupby(["season","winner"]).size().sort_values(ascending=False).head(10)

i.groupby("team1")["team1_runs"].max().sort_values(ascending=False)

mp=pd.concat([i["team1"],i["team2"]]).value_counts()
mp

wi=i["winner"].value_counts()
wi

e=(wi/mp)*100
e.sort_values(ascending=False)
e

e = (wi / mp) * 100
e = e.round(2)
e.sort_values(ascending=False,inplace=True)
e

e.sort_values().plot(
    kind="barh",
    figsize=(8, 5),
    title="Win Percentage of Teams"
)

e.sort_values().plot(
    kind="pie",
    figsize=(8, 5),
    title="Win Percentage of Teams"
)

e.sort_values().plot(
    kind="pie",
    figsize=(8, 5),
    title="Win Percentage of Teams"
)

e.sort_values().plot(
    kind="hist",
    figsize=(8, 5),
    title="Win Percentage of Teams"
)

#Exploratory data analysis

#1 used to analysze the pattern and investigate the data set than data visualization
#2 duscover the pattern,assumptions and trends help of statisticals summary and graphical representations
#3 EDA appproach to analyze the data using the visual technique

#sample vs population
#1 population - the data to be olllected
#2 sample - a portion of population

#types of data
#1- Qualitative
#2 -Quantitative

#norminal - category not a order
#ordinal -natural order-rank
#binary - two possible values

#discrete-counting the individual units and separate(counting) ==> does not depend not on the previous data
#continous-data often show trends in data over time.(tempearture,stock prices) ==> depends on the previous data

'''
#Statiscs--branch of applied mathematics focused on analyze,collection,analysis,organisation,interpretation,presentation of data
  #1.descriptive--describe
  #2.inferential--insights--findings(ml),conclusion,test hypothesis based on the larger population based on sample data


#1 ====Descriptive Statistics====
#i-measure of central tendency -mean,median,mode
#ii-measure of dispersion/spread/deviation - range,IQR,Standard DEviation,variance
#iii-measure of frequency
#iv -measure of distribution-kurtosis,skewness

#summarizing and organizing the data

#i-measure of central tendency

      #1 -MEAN
          #-->x=sum of all /number of data

          #x=sample mean
          #mu=population mean

      #2 -MEDIAN
        #arrange in ascending order
        #divded the data in two equal parts
        #median will be center value value if it is odd
        #median will be average if it is in even number

      #3 -MODE
        #most appearing mode or maximum appear on the data
        #1 - bimodal
        #2 - Trimodal
        #3 - multimodal

# ii measure of spread/dispresion
   #hhighest-lowest
   #1 Quartile
      #IQR Range- divided by 4
      #Intertertile -divided by 3
      #interQuintile-divide by 5

  #2 standard deviation -how much data is disprese from the mean ,spread the value awya from the mean
     #low sd==tightly clustered towards the mean
     #high sd == data points are widely spread from the mean
      #
     # \(\sigma =\sqrt{\frac{\sum (x_{i}-\mu )^{2}}{N}}\)

  #3 Variance
     # average of squared deviations

#iii frequency

     #frequence of an event
     #n represents the number of  event occured in the experiment
     #represent in histogram

"""

import pandas as pd

ai=pd.read_csv("/content/ai-impact-jobs-layoff-risk-dataset.csv")
ai

ai.info()

ai.head()

ai.isnull().sum()

ai[["Tasks_Automated_Percentage","Layoff_Risk"]]

ai.head()

ai[["Creativity_Requirement","AI_Adoption_Level",	"Number_of_AI_Tools_Used","Layoff_Risk"]].tail(10)

import matplotlib.pyplot as plt

ai[["Tasks_Automated_Percentage",
    "Years_of_Experience",
    "Routine_Task_Percentage",
    "Layoff_Risk"]].plot(
        kind="bar",
        figsize=(20, 10)
)

plt.show()

# Dataset shape
ai.shape

# Data types
ai.dtypes

# Statistical summary
ai.describe()

# Unique values
ai.nunique()



# Distribution
ai.hist(figsize=(15,10))

ai["Layoff_Risk"].value_counts()

import seaborn as sns
sns.boxplot(data=ai, x="Layoff_Risk",
            y="Tasks_Automated_Percentage")

sns.boxplot(data=ai, x="Layoff_Risk",
            y="AI_Usage_Hours_Per_Week")

sns.scatterplot(
    data=ai,
    x="AI_Adoption_Level",
    y="Tasks_Automated_Percentage",
    hue="Layoff_Risk"
)

sns.heatmap(
    ai.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

